"""Email notifications using Resend (alternative to Gmail SMTP)."""
import os
import json
import logging
from datetime import datetime
from pathlib import Path

import config

log = logging.getLogger(__name__)

def send_notification_resend(proposals: list[dict], stats: dict, dry_run: bool = False):
    """Send email notification using Resend API.
    
    Args:
        proposals: List of proposal dicts to include in email
        stats: Monitor stats dict
        dry_run: If True, don't actually send email
        
    Returns:
        bool: True if sent successfully (or dry-run), False otherwise
    """
    try:
        import resend
    except ImportError:
        log.warning("resend package not installed. Install with: pip install resend")
        return False
    
    # Get API key
    resend_key = os.getenv("RESEND_API_KEY")
    if not resend_key:
        log.error("RESEND_API_KEY not set in environment")
        return False
    
    resend.api_key = resend_key
    
    # Email config
    from_email = os.getenv("RESEND_FROM_EMAIL", "onboarding@resend.dev")  # Use your verified domain
    to_email = os.getenv("RESEND_TO_EMAIL")
    
    if not to_email:
        log.error("RESEND_TO_EMAIL not set in environment")
        return False
    
    # Build email content
    subject = f"🎯 {len(proposals)} New Upwork Proposals Generated"
    
    html_body = f"""
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2>🎯 Upwork Proposal Report</h2>
        <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
        
        <h3>📊 Summary</h3>
        <ul>
            <li>Jobs Matched: {stats.get('jobs_matched', 0)}</li>
            <li>Proposals Generated: {stats.get('proposals_generated', 0)}</li>
            <li>Failed: {stats.get('proposals_failed', 0)}</li>
        </ul>
        
        <h3>✍️ Proposals ({len(proposals)})</h3>
    """
    
    for i, prop in enumerate(proposals[:10], 1):  # Max 10 in email
        html_body += f"""
        <div style="border-left: 3px solid #14a800; padding: 10px; margin: 10px 0; background: #f5f5f5;">
            <h4>{i}. {prop.get('title', 'Untitled')[:60]}...</h4>
            <p><strong>Match Score:</strong> {prop.get('match_score', 0):.1f}/100</p>
            <p><strong>Status:</strong> {prop.get('status', 'pending_review')}</p>
            <p style="font-size: 12px; color: #666;">
                {prop.get('proposal_text', '')[:200]}...
            </p>
        </div>
        """
    
    if len(proposals) > 10:
        html_body += f"<p><em>+ {len(proposals) - 10} more proposals in dashboard</em></p>"
    
    html_body += """
        <hr>
        <p><a href="http://localhost:8501" style="color: #14a800;">📊 View Full Dashboard</a></p>
        <p style="font-size: 12px; color: #999;">
            Generated by Upwork Proposal Automation System
        </p>
    </body>
    </html>
    """
    
    if dry_run:
        log.info(f"DRY RUN: Would send email to {to_email}")
        print(f"  📧 DRY RUN: Email to {to_email} (subject: {subject})")
        return True
    
    try:
        # Send via Resend
        response = resend.Emails.send({
            "from": from_email,
            "to": to_email,
            "subject": subject,
            "html": html_body
        })
        
        log.info(f"Email sent successfully via Resend: {response}")
        print(f"  ✅ Email sent to {to_email}")
        return True
        
    except Exception as e:
        log.error(f"Failed to send email via Resend: {e}")
        print(f"  ❌ Email failed: {e}")
        return False
