#!/bin/bash

echo "🧪 Testing Proposal Generation"
echo ""
echo "Available providers based on priority:"
echo "  1. Groq (fastest, cheapest) - NOT SET"
echo "  2. OpenAI (high quality) - ✅ AVAILABLE"  
echo "  3. Gemini - NOT SET"
echo "  4. xAI Grok - ✅ AVAILABLE"
echo "  5. Ollama (local fallback)"
echo ""
echo "Will use: OpenAI (highest priority available)"
echo ""
echo "Run this command to test:"
echo ""
echo "source .venv/bin/activate && python test_groq_proposal.py"
echo ""
echo "Or to use xAI instead, unset OPENAI_API_KEY first:"
echo "unset OPENAI_API_KEY && python test_groq_proposal.py"
